# Generated by Django 4.0.6 on 2023-02-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorname', models.CharField(max_length=255)),
                ('sensordatatype', models.CharField(max_length=255)),
                ('sensormodel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tempdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('sensor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.sensors')),
            ],
        ),
        migrations.CreateModel(
            name='infradata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('infra', models.FloatField()),
                ('sensor3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.sensors')),
            ],
        ),
        migrations.CreateModel(
            name='humidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField()),
                ('sensor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.sensors')),
            ],
        ),
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buzzer', models.BooleanField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.infradata')),
            ],
        ),
    ]
